Hud width
HC-Interns/minersweeper pull request #85
Opened 2018-08-08 22:31 UTC by JettTech

Literally just adds a max-width to each of the direct children of the hud component and changes one flexbox style. 

This commit also includes updates to the username length truncation.

2018-08-08 22:36 UTC, maackle requested changes

2018-08-08 22:36 UTC, maackle commented on ui-src/src/components/Chatbox.tsx
> +    username = authorName.substring(0,15);
What if we also add a "..." ?

2018-08-08 22:36 UTC, maackle commented on ui-src/src/components/Chatbox.tsx
> +    username = authorName.substring(0,15);
And also could make this a function since the same code is copied 3x

2018-08-09 02:47 UTC, willemolding submitted a review, later dismissed
sl

2018-08-09 04:59 UTC, maackle approved these changes

2018-08-09 04:59 UTC, merged